create or replace PROCEDURE P_BACKUP_TABLE (P_NOMBRE_TABLA VARCHAR2) IS
    V_NOMBRE_TABLA_BACKUP VARCHAR2(30) := P_NOMBRE_TABLA || '_' || TO_CHAR(SYSDATE, 'DDMMYYYYHH24');
BEGIN
    BEGIN
        EXECUTE IMMEDIATE 'DROP TABLE ' || V_NOMBRE_TABLA_BACKUP;
    EXCEPTION 
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('ERROR CONTROLADO');
    END;
    EXECUTE IMMEDIATE 'CREATE TABLE ' || V_NOMBRE_TABLA_BACKUP 
        || ' AS SELECT * FROM ' || P_NOMBRE_TABLA;

END;