set serveroutput on;

DECLARE
    --VARIABLES
    V_NOMBRE EMPLOYEES.FIRST_NAME%TYPE;
    V_EDAD NUMBER := 22;
BEGIN
    V_NOMBRE := 'JUAN'; 
    --COMENTARIO DE UNA LINEA
    DBMS_OUTPUT.PUT_LINE('HOLA ' || V_NOMBRE || '('|| V_EDAD || ')');

    IF V_EDAD<25 THEN
        DBMS_OUTPUT.PUT_LINE('AUN ES COLAGENO');
    --ELSIF V_EDAD >= 25 AND V_EDAD <= 30 THEN
    ELSIF V_EDAD BETWEEN 25 AND 30 THEN
        DBMS_OUTPUT.PUT_LINE('CASI LE DA EL VIEJAZO');
    ELSE 
        DBMS_OUTPUT.PUT_LINE('LE DIO EL VIEJAZO');
    END IF;

    /*
    COMENTARIOS DE VARIAS
    LINEAS
    */
END;












DECLARE
    V_FIRST_NAME EMPLOYEES.FIRST_NAME%TYPE; 
    V_LAST_NAME EMPLOYEES.LAST_NAME%TYPE; 
BEGIN
    SELECT FIRST_NAME, LAST_NAME
    INTO V_FIRST_NAME, V_LAST_NAME
    FROM EMPLOYEES
    WHERE EMPLOYEE_ID = 99999;
    
    DBMS_OUTPUT.PUT_LINE(V_FIRST_NAME || ' ' || V_LAST_NAME);
EXCEPTION
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('OCURRIO UNN ERROR' );
    DBMS_OUTPUT.PUT_LINE('SQL CODE: ' || SQLCODE);
    DBMS_OUTPUT.PUT_LINE('SQL ERROR: ' || SQLERRM);
END;


DECLARE
    V_EMPLOYEE EMPLOYEES%ROWTYPE;
BEGIN
    SELECT *
    INTO V_EMPLOYEE
    FROM EMPLOYEES
    WHERE EMPLOYEE_ID = 100;
    
    DBMS_OUTPUT.PUT_LINE(V_EMPLOYEE.FIRST_NAME || ' ' || V_EMPLOYEE.LAST_NAME|| '--' || V_EMPLOYEE.SALARY);
EXCEPTION
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('OCURRIO UNN ERROR' );
    DBMS_OUTPUT.PUT_LINE('SQL CODE: ' || SQLCODE);
    DBMS_OUTPUT.PUT_LINE('SQL ERROR: ' || SQLERRM);
END;


--CURSORES









