SELECT * FROM EMPLOYEES;

SELECT * FROM JOBS;

DELETE FROM EMPLOYEES
WHERE EMPLOYEE_ID IN (666, 207);

SELECT * FROM DEPARTMENTS;


COMMIT;


-- MOSTRAR TODOS LOS EMPLEADOS CON SU DEPARTAMENTO
-- TIPOS DE JOINS, LEFT, RIGHT, INNER, FULL OUTER JOIN
SELECT COUNT(*) FROM EMPLOYEES;


SELECT  A.FIRST_NAME, 
        A.LAST_NAME, 
        B.DEPARTMENT_NAME, 
        A.DEPARTMENT_ID
FROM EMPLOYEES A
LEFT JOIN DEPARTMENTS B
ON (A.DEPARTMENT_ID = B.DEPARTMENT_ID);


-- MOSTRAR SOLO LOS EMPLEADOS CON DEPARTAMENTO 
--- Y LOS DEPARTAMENTOS QUE NO TENGAN EMPLEADOS
SELECT  A.FIRST_NAME, 
        A.LAST_NAME, 
        B.DEPARTMENT_NAME, 
        B.DEPARTMENT_ID
FROM EMPLOYEES A
RIGHT JOIN DEPARTMENTS B
ON (A.DEPARTMENT_ID = B.DEPARTMENT_ID);

-- MOSTRAR TODOS LOS EMPLEADOS AUNQUE NO TENGAN DEPARTAMENTO
-- Y MOSTRAR TODOS LOS DEPARTAMENTOS QUE NO TENGAN EMPLEADOS
SELECT  A.FIRST_NAME, 
        A.LAST_NAME, 
        B.DEPARTMENT_NAME, 
        B.DEPARTMENT_ID
FROM EMPLOYEES A
FULL OUTER JOIN DEPARTMENTS B
ON (A.DEPARTMENT_ID = B.DEPARTMENT_ID);


--MOSTRAR LOS EMPLEADOS QUE NO TIENEN DEPARTAMENTO
SELECT  A.FIRST_NAME, 
        A.LAST_NAME, 
        B.DEPARTMENT_NAME, 
        A.DEPARTMENT_ID
FROM EMPLOYEES A
LEFT JOIN DEPARTMENTS B
ON (A.DEPARTMENT_ID = B.DEPARTMENT_ID)
WHERE B.DEPARTMENT_ID IS NULL;

--DEPARTAMENTOS SIN EMPLEADOS
SELECT  A.FIRST_NAME, 
        A.LAST_NAME, 
        B.DEPARTMENT_NAME, 
        B.DEPARTMENT_ID
FROM EMPLOYEES A
RIGHT JOIN DEPARTMENTS B
ON (A.DEPARTMENT_ID = B.DEPARTMENT_ID)
WHERE A.EMPLOYEE_ID IS NULL;


-- EMPLEADOS SIN DEPARTAMENTOS Y DEPARTAMENTOS SIN EMPLEADOS
SELECT  A.FIRST_NAME, 
        A.LAST_NAME, 
        B.DEPARTMENT_NAME, 
        B.DEPARTMENT_ID
FROM EMPLOYEES A
FULL OUTER JOIN DEPARTMENTS B
ON (A.DEPARTMENT_ID = B.DEPARTMENT_ID)
WHERE B.DEPARTMENT_ID IS NULL OR A.EMPLOYEE_ID IS NULL;

SELECT COUNT(*) -- 107
FROM EMPLOYEES;

SELECT COUNT(*) -- 27
FROM DEPARTMENTS;


-- ESTO ES UN INNER JOIN USANDO PRODUCTOS CARTESIANOS
SELECT A.FIRST_NAME, 
        A.LAST_NAME, 
        B.DEPARTMENT_NAME, 
        A.DEPARTMENT_ID  --2889
FROM    EMPLOYEES A, 
        DEPARTMENTS B
WHERE A.DEPARTMENT_ID = B.DEPARTMENT_ID; --PRODUCTO CARTESIANNO


-- ESTO ES UN LEFT JOIN USANDO PRODUCTOS CARTESIANOS
SELECT A.FIRST_NAME, 
        A.LAST_NAME, 
        B.DEPARTMENT_NAME, 
        A.DEPARTMENT_ID  --2889
FROM    EMPLOYEES A, 
        DEPARTMENTS B
WHERE A.DEPARTMENT_ID = B.DEPARTMENT_ID (+) --PRODUCTO CARTESIANNO

UNION 
-- ESTO ES UN RIGHT JOIN USANDO PRODUCTOS CARTESIANOS
SELECT A.FIRST_NAME, 
        A.LAST_NAME, 
        B.DEPARTMENT_NAME, 
        A.DEPARTMENT_ID  --2889
FROM    EMPLOYEES A, 
        DEPARTMENTS B
WHERE A.DEPARTMENT_ID(+) = B.DEPARTMENT_ID;



SELECT  A.FIRST_NAME || ' ' || A.LAST_NAME AS FULL_NAME,
        B.FIRST_NAME || ' ' || B.LAST_NAME AS MANAGER_FULL_NAME,
        C.FIRST_NAME || ' ' || C.LAST_NAME AS MANAGER_OF_MANAGER_FULL_NAME
FROM EMPLOYEES A
LEFT JOIN EMPLOYEES B
ON (A.MANAGER_ID = B.EMPLOYEE_ID)
LEFT JOIN EMPLOYEES C 
ON (B.MANAGER_ID = C.EMPLOYEE_ID);


SELECT  A.FIRST_NAME || ' ' || A.LAST_NAME AS FULL_NAME,
        B.FIRST_NAME || ' ' || B.LAST_NAME AS MANAGER_FULL_NAME,
        C.FIRST_NAME || ' ' || C.LAST_NAME AS MANAGER_OF_MANAGER_FULL_NAME
FROM    EMPLOYEES A,
        EMPLOYEES B,
        EMPLOYEES C
WHERE   A.MANAGER_ID = B.EMPLOYEE_ID (+)
AND     B.MANAGER_ID = C.EMPLOYEE_ID (+);






