SET SERVEROUTPUT ON;

DECLARE
    V_RESULTADO VARCHAR2(500);
    V_CODIGO_RESULTADO NUMBER;
BEGIN
    P_INSERTAR_SECCION (
        P_CODIGO_ALTERNO => '1600',
        P_HORA_INICIO => to_date('16:00','HH24:MI'),
        P_HORA_FIN => to_date('15:00','HH24:MI'),
        P_DIAS => 'LMMIJV',
        P_CODIGO_AULA => 3,
        P_NOMBRE_ASIGNATURA => 'Bases de datos II',
        P_NOMBRE_MAESTRO => 'PERSONA9 APELLIDO9',
        P_CODIGO_PERIODO => 3,
        P_CANTIDAD_CUPOS => 999,
        P_MENSAJE_RESULTADO => V_RESULTADO,
        P_CODIGO_RESULTADO => V_CODIGO_RESULTADO
    );
    
    DBMS_OUTPUT.PUT_LINE('PARAMETRO DE SALIDA: ' || V_RESULTADO);
    DBMS_OUTPUT.PUT_LINE('PARAMETRO DE SALIDA: ' || V_CODIGO_RESULTADO);
END;


DECLARE 
    RESULTADO BOOLEAN;
BEGIN
    PKG_ALUMNOS.p_insertar;
    RESULTADO := PKG_ALUMNOS.F_ELIMINAR('');
    IF (RESULTADO) THEN
        DBMS_OUTPUT.PUT_LINE('RETORNO VERDADERO');
    END IF;
END;