create or replace PACKAGE PKG_ALUMNOS AS
    VARIABLE_X VARCHAR2(500);
    
    PROCEDURE P_INSERTAR (P_NOMBRE VARCHAR2); --DECLARACION
    PROCEDURE P_INSERTAR (P_NOMBRE VARCHAR2, P_APELLIDO VARCHAR2); 
    PROCEDURE P_ACTUALIZAR (P_NOMBRE VARCHAR2);
    FUNCTION F_ELIMINAR (P_NOMBRE VARCHAR2) RETURN BOOLEAN;
END PKG_ALUMNOS; 



create or replace PACKAGE BODY PKG_ALUMNOS AS
    PROCEDURE P_INSERTAR (P_NOMBRE VARCHAR2) AS
    BEGIN
        --VALIDACIONES
        --INSERT
        NULL;
    EXCEPTION 
        WHEN OTHERS THEN 
            NULL;
    END P_INSERTAR;
    
    PROCEDURE P_INSERTAR (P_NOMBRE VARCHAR2, P_APELLIDO VARCHAR2) AS
    BEGIN
        P_INSERTAR(P_NOMBRE);
        --VALIDACIONES
        --INSERT
        NULL;
    EXCEPTION 
        WHEN OTHERS THEN 
            NULL;
    END P_INSERTAR;

    PROCEDURE P_ACTUALIZAR (P_NOMBRE VARCHAR2) AS
    BEGIN
        NULL;
    END P_ACTUALIZAR;

    FUNCTION F_ELIMINAR (P_NOMBRE VARCHAR2) RETURN BOOLEAN AS
    BEGIN
        RETURN TRUE;
    END F_ELIMINAR;
END PKG_ALUMNOS; 