create or replace PROCEDURE P_ACTUALIZAR_SUSCRIPTORES
(
    P_CODIGO_CANAL TBL_CANALES.CODIGO_CANAL%TYPE,
    P_CODIGO_USUARIO TBL_USUARIOS.CODIGO_USUARIO%TYPE,
    P_MENSAJE_RESULTADO OUT VARCHAR
) AS
    V_CODIGO_CANAL TBL_CANALES.CODIGO_CANAL%TYPE;
    V_CODIGO_USUARIO TBL_USUARIOS.CODIGO_USUARIO%TYPE;
    V_CODIGO_USUARIO_DUENIO  TBL_USUARIOS.CODIGO_USUARIO%TYPE;
    V_CANTIDAD_USUARIOS_CANAL NUMBER;
    V_EXCEPCION_CANAL EXCEPTION;
    V_EXCEPCION_USUARIO EXCEPTION;
BEGIN
    BEGIN
        SELECT CODIGO_CANAL, CODIGO_USUARIO
        INTO V_CODIGO_CANAL, V_CODIGO_USUARIO_DUENIO
        FROM TBL_CANALES
        WHERE CODIGO_CANAL = P_CODIGO_CANAL;
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE V_EXCEPCION_CANAL;
    END;

    BEGIN
        SELECT CODIGO_USUARIO
        INTO V_CODIGO_USUARIO
        FROM TBL_USUARIOS
        WHERE CODIGO_USUARIO = P_CODIGO_USUARIO;
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE V_EXCEPCION_USUARIO;
    END;    

    ---
    INSERT INTO TBL_USUARIOS_X_CANAL(CODIGO_USUARIO, CODIGO_CANAL, FECHA_SUSCRIPCION)
    VALUES (P_CODIGO_USUARIO, P_CODIGO_CANAL, SYSDATE);


    SELECT COUNT(1) CANTIDAD_USUARIOS
    INTO V_CANTIDAD_USUARIOS_CANAL
    FROM TBL_USUARIOS_X_CANAL
    WHERE CODIGO_CANAL = P_CODIGO_CANAL;

    UPDATE TBL_CANALES
    --SET CANTIDAD_SUSCRIPTORES = NVL(CANTIDAD_SUSCRIPTORES, 0) + 1
    SET CANTIDAD_SUSCRIPTORES = V_CANTIDAD_USUARIOS_CANAL
    WHERE CODIGO_CANAL = P_CODIGO_CANAL;

    IF V_CANTIDAD_USUARIOS_CANAL = 6 THEN    
        P_GUARDAR_NOTIFICACION(
            P_codigo_usuario_origen => NULL,
            P_codigo_usuario_destino => V_CODIGO_USUARIO_DUENIO,
            P_texto_notificacion => 'FELICIDADES LLEGASTE A LA META',
            P_codigo_videO => NULL
        );
    END IF;
    P_MENSAJE_RESULTADO := 'USUARIO SUSCRITO';
    COMMIT;
EXCEPTION
WHEN V_EXCEPCION_CANAL THEN
    P_MENSAJE_RESULTADO := 'EL CANAL NO EXISTE'; 
    ROLLBACK;
WHEN V_EXCEPCION_USUARIO THEN
    P_MENSAJE_RESULTADO := 'EL USUARIO NO EXISTE';
    ROLLBACK;
END;