DECLARE
    V_RESULTADO VARCHAR2(400);
BEGIN
    P_ACTUALIZAR_SUSCRIPTORES(3, 10, V_RESULTADO);
    DBMS_OUTPUT.PUT_LINE (V_RESULTADO);
END;


SELECT NVL(NULL, 0) + 1 FROM DUAL;

SELECT * FROM TBL_NOTIFICACIONES;

SELECT CODIGO_CANAL, COUNT(1) CANTIDAD_USUARIOS
FROM TBL_USUARIOS_X_CANAL
WHERE CODIGO_CANAL = 3
GROUP BY CODIGO_CANAL;

SELECT * FROM TBL_USUARIOS;


SELECT * FROM TBL_USUARIOS_X_CANAL;

BEGIN
    P_GUARDAR_NOTIFICACION(
        P_codigo_usuario_origen => 1,
        P_codigo_usuario_destino => 2,
        P_texto_notificacion => 'FELICIDADES LLEGASTE A LA META',
        P_codigo_videO => 1
    );
END;
SELECT * FROM TBL_NOTIFICACIONES;

CREATE SEQUENCE SEQ_CODIGO_NOTIFICACION;

SELECT * FROM TBL_CANALES;







CREATE SEQUENCE SEQ_CODIGO_VIDEO;

SELECT * FROM TBL_NOTIFICACIONES;
SELECT * FROM TBL_VIDEOS;
SELECT SEQ_CODIGO_VIDEO.NEXTVAL FROM DUAL;

SET SERVEROUTPUT ON;

DECLARE 
    V_CODIGO_VIDEO TBL_VIDEOS.CODIGO_VIDEO%TYPE;
    V_RESULTADO VARCHAR2(1000);
BEGIN
    P_GUARDAR_VIDEO(
        P_CODIGO_VIDEO=> V_CODIGO_VIDEO,
        P_CODIGO_USUARIO=> 1,
        P_CODIGO_ESTADO_VIDEO=> 1,
        P_CODIGO_IDIOMA=> 1,
        P_CODIGO_CANAL=> 3,
        P_NOMBRE_VIDEO=> 'Gatitos bailando kpop cristiano',
        P_RESOLUCION=> '1234',
        P_DURACION_SEGUNDOS=> '123123',
        P_CANTIDAD_LIKES=> '121',
        P_CANTIDAD_DISLIKES=> '0',
        P_CANTIDAD_VISUALIZACIONES=> '43554',
        P_FECHA_SUBIDA=> sysdate,
        P_DESCRIPCION=> 'Los mejores gatitos de la web',
        P_CANTIDAD_SHARES=> '324',
        P_URL=> 'localhost',
        P_MENSAJE_RESULTADO => V_RESULTADO
    );
    dbms_output.put_line('RESULTADO: ' || V_RESULTADO); 
    dbms_output.put_line('CODIGO VIDEO GUARDADO: ' || V_CODIGO_VIDEO);
END;

CREATE SEQUENCE SEQ_CODIGO_COMENTARIO;


SELECT * FROM TBL_COMENTARIOS;

DECLARE
    V_CODIGO_COMENTARIO NUMBER;
    V_RESULTADO VARCHAR2(1000);
BEGIN
    P_GUARDAR_COMENTARIO (
        P_CODIGO_COMENTARIO => V_CODIGO_COMENTARIO,
        P_CODIGO_COMENTARIO_PADRE => NULL,
        P_CODIGO_USUARIO => 1,
        P_CODIGO_VIDEO => 2,
        P_COMENTARIO => 'QUE BOMGNITO VIDEO DE GATITOS OTAKUS',
        P_MENSAJE_RESULTADO => V_RESULTADO
    );
END;

SELECT * FROM TBL_VIDEOS;

SELECT * FROM TBL_COMENTARIOS;
SELECT * FROM TBL_NOTIFICACIONES;